### ISSUE TITLE
Html Struktur für Shogi-Webseite (Spielbrett und Gefängnis)

### ISSUE THREAD

**Issue by Krayaty** [SeelenBacken/Shogi#1]
Erstellen der Website für das Shogi Spiel und Aufbau der wesentlichen Elemente wie Spielbrett und Gefängnis. Nur optische Anpassungen, keine Spiellogik.

**Comment by SeelenBacken** [comment]
Spielbereich im Holz-Look, oder nur 2 Farbig? Und welche Farben?
![image](https://user-images.githubusercontent.com/57874287/84641782-d7df9580-aefb-11ea-8929-cf0d0d0afd9f.png)

**Comment by Krayaty** [comment]
Ich bin für zweifarbig.

**Comment by gearwheel01** [comment]
normalerweise ist das Spielbrett einfarbig

**Comment by SeelenBacken** [comment]
![image](https://user-images.githubusercontent.com/57874287/85007350-ae24a980-b15b-11ea-9507-de28996fb4dd.png)
Look normal
![image](https://user-images.githubusercontent.com/57874287/85007375-bc72c580-b15b-11ea-8e22-d981a5f4c871.png)
Highlighting Farbe

Standartfarben für Spielbrett und das Highlighting, welche Felder verfügbar sind, welche sollen wir da nehmen? Andere Vorschläge/Wünsche?
